apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-and-push
spec:
  params:
    - default: Unknown commit
      description: The commit comment from the push notification
      name: commit-comment
      type: string
  resources:
    - name: service-domain-git
      type: git
    - name: service-domain-image
      type: image
  tasks:
    - name: echo-git-commit-comment
      params:
        - name: comment
          value: $(params.commit-comment)
      taskRef:
        kind: Task
        name: echo-git-commit-comment

