apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: service-domain-triggertemplate
  namespace: dm
spec:
  params:
    - name: gitrepositoryurl
      description: The git repository url
    - name: comment-string
      description: The comment string
    - name: namespace
      description: namespace to deploy into
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: service-domain-build-$(uid)
        namespace: dm
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: build-and-push
        params:
        - name: commit-comment
          value: $(params.comment-string)
        resources:
          - name: service-domain-git
            resourceSpec:
              type: git
              params:
              - name: url
                value: $(params.gitrepositoryurl)
          - name: service-domain-image
            resourceSpec:
              type: image
              params:
                - name: url
                  value: image-registry.openshift-image-registry.svc:5000/$(params.namespace)/service-domain:latest


---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: service-domain-pipelinebinding
  namespace: dm
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: pipeline
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
    - name: comment-string
      value: $(body.head_commit.message)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: service-domain-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: service-domain-pipelinebinding
    template:
      name: service-domain-triggertemplate